export const CREATE_APPOINTMENT = 'CREATE_APPOINTMENT'
export const UPDATE_APPOINTMENT = 'UPDATE_APPOINTMENT'
export const FETCH_ALL_APPOINTMENTS = 'FETCH_ALL_APPOINTMENTS'
export const FETCH_APPOINTMENT = 'FETCH_APPOINTMENT'
export const DELETE_APPOINTMENT = 'DELETE_APPOINTMENT'

export const CREATE_TEST = 'CREATE_TEST'
export const UPDATE_TEST = 'UPDATE_TEST'
export const FETCH_ALL_TESTS = 'FETCH_ALL_TESTS'
export const FETCH_TEST = 'FETCH_TEST'
export const DELETE_TEST = 'DELETE_TEST'

export const CREATE_PRESCRIPTION = 'CREATE_PRESCRIPTION'
export const UPDATE_PRESCRIPTION = 'UPDATE_PRESCRIPTION'
export const FETCH_ALL_PRESCRIPTIONS = 'FETCH_ALL_PRESCRIPTIONS'
export const FETCH_PRESCRIPTION = 'FETCH_PRESCRIPTION'
export const DELETE_PRESCRIPTION = 'DELETE_PRESCRIPTION'

export const CREATE_MEDICINE = 'CREATE_MEDICINE'
export const UPDATE_MEDICINE = 'UPDATE_MEDICINE'
export const FETCH_ALL_MEDICINES = 'FETCH_ALL_MEDICINES'
export const FETCH_MEDICINE = 'FETCH_MEDICINE'
export const DELETE_MEDICINE = 'DELETE_MEDICINE'

export const CREATE_USER = 'CREATE_USER'
export const UPDATE_USER = 'UPDATE_USER'
export const FETCH_ALL_USERS = 'FETCH_ALL_USERS'
export const FETCH_USER = 'FETCH_USER'
export const DELETE_USER = 'DELETE_USER'

export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE'


export const AUTH = 'AUTH'
export const LOGOUT = 'LOGOUT'
export const STATUS = 'STATUS'