export const CREATE_APPOINTMENT = 'CREATE_APPOINTMENT'
export const UPDATE_APPOINTMENT = 'UPDATE_APPOINTMENT'
export const FETCH_ALL_APPOINTMENTS = 'FETCH_ALL_APPOINTMENTS'
export const FETCH_APPOINTMENT = 'FETCH_APPOINTMENT'
export const DELETE_APPOINTMENT = 'DELETE_APPOINTMENT'

export const CREATE_PRESCRIPTION = 'CREATE_PRESCRIPTION'
export const UPDATE_PRESCRIPTION = 'UPDATE_PRESCRIPTION'
export const FETCH_ALL_PRESCRIPTIONS = 'FETCH_ALL_PRESCRIPTIONS'
export const FETCH_PRESCRIPTION = 'FETCH_PRESCRIPTION'
export const DELETE_PRESCRIPTION = 'DELETE_PRESCRIPTION'

export const CREATE_USER = 'CREATE_USER'
export const UPDATE_USER = 'UPDATE_USER'
export const FETCH_ALL_USERS = 'FETCH_ALL_USERS'
export const FETCH_USER = 'FETCH_USER'
export const DELETE_USER = 'DELETE_USER'


export const AUTH = 'AUTH'
export const LOGOUT = 'LOGOUT'